version: "3.9"

services:
  mongo-master:
    build:
      context: ./
      dockerfile: Dockerfile-master
    container_name: mongo-master
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
